CREATE DATABASE IF NOT EXISTS `audit_management`
USE `audit_management`;

CREATE TABLE IF NOT EXISTS `audit_log` (
  `log_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `item_id` int(11) NOT NULL COMMENT 'checklist_items 테이블 참조',
  `actual_value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '실제 측정값' CHECK (json_valid(`actual_value`)),
  `passed` tinyint(1) DEFAULT NULL COMMENT '통과 여부 (1:통과, 0:실패, NULL:대기)',
  `notes` text DEFAULT NULL COMMENT '비고',
  `exclude_reason` varchar(255) DEFAULT NULL COMMENT '점수 제외 사유',
  `checked_at` timestamp NULL DEFAULT current_timestamp() COMMENT '점검 일시',
  PRIMARY KEY (`log_id`),
  KEY `idx_user_item` (`user_id`,`item_id`),
  KEY `idx_checked_at` (`checked_at`),
  KEY `fk_audit_log_item` (`item_id`),
  KEY `idx_audit_log_user_item_date` (`user_id`,`item_id`,`checked_at`),
  CONSTRAINT `fk_audit_log_item` FOREIGN KEY (`item_id`) REFERENCES `checklist_items` (`item_id`),
  CONSTRAINT `fk_audit_log_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보안 감사 로그';

CREATE TABLE IF NOT EXISTS `checklist_items` (
  `item_id` int(11) NOT NULL AUTO_INCREMENT,
  `item_name` varchar(255) NOT NULL COMMENT '점검 항목명',
  `category` varchar(100) NOT NULL COMMENT '카테고리',
  `description` text DEFAULT NULL COMMENT '상세 설명',
  `check_type` enum('daily','manual') NOT NULL DEFAULT 'daily' COMMENT '점검 유형 (정기/수시)',
  `check_frequency` varchar(50) DEFAULT 'daily' COMMENT '점검 주기',
  `penalty_weight` decimal(3,1) DEFAULT 0.5 COMMENT '감점 가중치 (기본 0.5점)',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`item_id`),
  KEY `idx_check_type` (`check_type`),
  KEY `idx_category` (`category`),
  KEY `idx_checklist_items_type` (`check_type`,`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='보안 점검 항목';

CREATE TABLE IF NOT EXISTS `department_exceptions` (
  `exception_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `department` varchar(100) NOT NULL COMMENT '부서명',
  `item_id` varchar(255) NOT NULL COMMENT '항목 ID (audit: 숫자, education/training: 문자열)',
  `item_type` enum('audit','education','training') NOT NULL COMMENT '항목 유형',
  `item_name` varchar(255) NOT NULL COMMENT '항목명',
  `item_category` varchar(100) NOT NULL COMMENT '항목 카테고리',
  `exclude_reason` varchar(255) NOT NULL COMMENT '제외 사유',
  `exclude_type` enum('permanent','temporary') DEFAULT 'permanent' COMMENT '제외 유형',
  `start_date` date DEFAULT NULL COMMENT '제외 시작일 (temporary인 경우)',
  `end_date` date DEFAULT NULL COMMENT '제외 종료일 (temporary인 경우)',
  `created_by` varchar(50) NOT NULL COMMENT '설정한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  PRIMARY KEY (`exception_id`),
  UNIQUE KEY `uk_dept_item_exception` (`department`,`item_id`,`item_type`),
  KEY `idx_department` (`department`),
  KEY `idx_item_type` (`item_type`),
  KEY `idx_active` (`is_active`),
  KEY `idx_dept_exceptions_search` (`department`,`item_type`,`is_active`),
  KEY `idx_item_search` (`item_id`,`item_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='통합 부서별 예외 설정 테이블';

CREATE TABLE IF NOT EXISTS `department_extended_exceptions` (
  `dept_exception_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `department` varchar(100) NOT NULL COMMENT '부서명',
  `item_id` varchar(100) NOT NULL COMMENT '항목 ID (정수형: 감사항목, 문자형: 교육/훈련)',
  `item_type` enum('audit_item','training_period','education_period') NOT NULL COMMENT '항목 유형',
  `item_name` varchar(255) NOT NULL COMMENT '항목명 (비정규화)',
  `item_category` varchar(100) NOT NULL COMMENT '항목 카테고리 (비정규화)',
  `exclude_reason` varchar(500) NOT NULL COMMENT '제외 사유',
  `exclude_type` enum('permanent','temporary') DEFAULT 'permanent' COMMENT '제외 유형',
  `start_date` date DEFAULT NULL COMMENT '제외 시작일 (temporary인 경우)',
  `end_date` date DEFAULT NULL COMMENT '제외 종료일 (temporary인 경우)',
  `created_by` varchar(50) NOT NULL COMMENT '설정한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  PRIMARY KEY (`dept_exception_id`),
  UNIQUE KEY `uk_dept_extended_exception` (`department`,`item_id`,`item_type`),
  KEY `idx_department_extended` (`department`),
  KEY `idx_item_type_dept_extended` (`item_type`),
  KEY `idx_active_dept_extended` (`is_active`),
  KEY `idx_dept_item_category` (`item_category`),
  KEY `idx_dept_extended_search` (`department`,`item_type`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='부서별 확장 감사 항목 제외 설정 (감사/교육/훈련)';

CREATE TABLE IF NOT EXISTS `department_item_exceptions` (
  `dept_exception_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `department` varchar(100) NOT NULL COMMENT '부서명',
  `item_id` int(11) NOT NULL COMMENT 'checklist_items 테이블 참조',
  `exclude_reason` varchar(255) NOT NULL COMMENT '제외 사유',
  `exclude_type` enum('permanent','temporary') DEFAULT 'permanent' COMMENT '제외 유형',
  `start_date` date DEFAULT NULL COMMENT '제외 시작일 (temporary인 경우)',
  `end_date` date DEFAULT NULL COMMENT '제외 종료일 (temporary인 경우)',
  `created_by` varchar(50) NOT NULL COMMENT '설정한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  `item_type` varchar(50) DEFAULT 'audit' COMMENT '항목 유형 (audit/education/training)',
  `item_name` varchar(255) DEFAULT '' COMMENT '항목명 (중복 저장)',
  `item_category` varchar(100) DEFAULT '' COMMENT '항목 카테고리 (중복 저장)',
  PRIMARY KEY (`dept_exception_id`),
  UNIQUE KEY `uk_dept_item_exception` (`department`,`item_id`),
  KEY `idx_department` (`department`),
  KEY `idx_item_id_dept` (`item_id`),
  KEY `idx_active_dept` (`is_active`),
  KEY `idx_dept_exceptions_type` (`department`,`item_type`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='부서별 감사 항목 제외 설정';

CREATE TABLE IF NOT EXISTS `manual_check_items` (
  `item_id` int(11) NOT NULL AUTO_INCREMENT,
  `item_code` varchar(50) NOT NULL COMMENT '항목 코드',
  `item_name` varchar(255) NOT NULL COMMENT '점검 항목명',
  `item_category` varchar(100) NOT NULL COMMENT '카테고리',
  `description` text DEFAULT NULL COMMENT '상세 설명',
  `penalty_weight` decimal(3,1) DEFAULT 0.5 COMMENT '감점 가중치',
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`item_id`),
  UNIQUE KEY `uk_item_code` (`item_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수시 점검 항목';

CREATE TABLE IF NOT EXISTS `manual_check_periods` (
  `period_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `check_type` enum('seal_check','malware_scan','file_encryption') NOT NULL COMMENT '점검 유형',
  `period_year` int(11) NOT NULL COMMENT '점검 연도',
  `period_name` varchar(50) NOT NULL COMMENT '기간명 (Q1, Q2, 상반기 등)',
  `start_date` date NOT NULL COMMENT '점검 시작일',
  `end_date` date NOT NULL COMMENT '점검 종료일',
  `is_completed` tinyint(1) DEFAULT 0 COMMENT '완료 여부 (0: 미완료, 1: 완료)',
  `completed_at` timestamp NULL DEFAULT NULL COMMENT '완료 처리 시각',
  `completed_by` varchar(50) DEFAULT NULL COMMENT '완료 처리한 관리자',
  `description` text DEFAULT NULL COMMENT '기간 설명',
  `auto_pass_setting` tinyint(1) DEFAULT 1 COMMENT '자동 통과 처리 여부',
  `created_by` varchar(50) NOT NULL COMMENT '생성한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  PRIMARY KEY (`period_id`),
  UNIQUE KEY `uk_type_year_period` (`check_type`,`period_year`,`period_name`),
  KEY `idx_check_type` (`check_type`),
  KEY `idx_period_year` (`period_year`),
  KEY `idx_is_completed` (`is_completed`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수시 점검 기간 설정';

CREATE TABLE IF NOT EXISTS `manual_check_results` (
  `check_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블 참조',
  `check_item_code` varchar(50) NOT NULL DEFAULT 'seal_check' COMMENT '점검 항목 코드 (seal_check, malware_scan, file_encryption)',
  `source_ip` varchar(45) DEFAULT NULL COMMENT '출처 IP (악성코드/암호화에서 사용)',
  `check_year` int(11) NOT NULL COMMENT '점검 연도',
  `check_period` varchar(20) NOT NULL COMMENT '점검 기간',
  `check_date` datetime NOT NULL COMMENT '점검 실시 일시',
  `checker_name` varchar(100) NOT NULL COMMENT '점검자명',
  `seal_status` enum('normal','damaged','missing','replacement_needed') DEFAULT NULL COMMENT '봉인씰 상태',
  `seal_number` varchar(50) DEFAULT NULL COMMENT '봉인 번호',
  `seal_notes` text DEFAULT NULL COMMENT '봉인씰 관련 비고',
  `malware_scan_result` enum('clean','infected','scan_failed','not_performed') DEFAULT NULL COMMENT '악성코드 검사 결과',
  `threats_found` int(11) DEFAULT 0 COMMENT '발견된 위협 수',
  `threats_cleaned` tinyint(1) DEFAULT 0 COMMENT '치료 완료 여부',
  `antivirus_version` varchar(100) DEFAULT NULL COMMENT '백신 엔진 버전',
  `malware_notes` text DEFAULT NULL COMMENT '악성코드 검사 관련 비고',
  `malware_name` varchar(255) DEFAULT NULL COMMENT '악성코드명',
  `malware_classification` varchar(100) DEFAULT NULL COMMENT '악성코드 분류',
  `malware_path` text DEFAULT NULL COMMENT '악성코드 경로',
  `detection_item` varchar(255) DEFAULT NULL COMMENT '탐지 항목',
  `encryption_status` enum('fully_encrypted','not_encrypted','partially_encrypted','not_applicable') DEFAULT NULL COMMENT '암호화 상태',
  `files_scanned` int(11) DEFAULT 0 COMMENT '검사된 파일 수',
  `unencrypted_files` int(11) DEFAULT 0 COMMENT '미암호화 파일 수',
  `encryption_completed` tinyint(1) DEFAULT 0 COMMENT '암호화 조치 완료 여부',
  `encryption_notes` text DEFAULT NULL COMMENT '암호화 관련 비고',
  `round_number` varchar(20) DEFAULT NULL COMMENT '회차 정보 (161회차 등)',
  `ssn_included` tinyint(1) DEFAULT 0 COMMENT '주민등록번호 포함 여부',
  `overall_result` enum('pass','fail','partial') NOT NULL COMMENT '종합 점검 결과',
  `total_score` decimal(5,2) DEFAULT 0.00 COMMENT '총점',
  `penalty_points` decimal(5,2) DEFAULT 0.00 COMMENT '감점',
  `notes` text DEFAULT NULL COMMENT '전체 비고',
  `exclude_from_scoring` tinyint(1) DEFAULT 0 COMMENT '점수 산정 제외 여부',
  `exclude_reason` varchar(500) DEFAULT NULL COMMENT '제외 사유',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `period_id` bigint(20) DEFAULT NULL COMMENT '연결된 기간 ID',
  PRIMARY KEY (`check_id`),
  KEY `idx_user_period` (`user_id`,`check_year`,`check_period`),
  KEY `idx_check_date` (`check_date`),
  KEY `idx_overall_result` (`overall_result`),
  KEY `period_id` (`period_id`),
  KEY `idx_check_item_code` (`check_item_code`),
  KEY `idx_check_type_year_period` (`check_item_code`,`check_year`,`check_period`),
  KEY `idx_check_type_result` (`check_item_code`,`overall_result`),
  CONSTRAINT `manual_check_results_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`),
  CONSTRAINT `manual_check_results_ibfk_2` FOREIGN KEY (`period_id`) REFERENCES `manual_check_periods` (`period_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수시 점검 결과';

CREATE TABLE IF NOT EXISTS `phishing_training` (
  `training_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `period_id` bigint(20) NOT NULL COMMENT '훈련 기간 ID 참조',
  `training_year` int(11) NOT NULL COMMENT '훈련 연도',
  `email_sent_time` timestamp NULL DEFAULT NULL COMMENT '메일발송시각',
  `action_time` timestamp NULL DEFAULT NULL COMMENT '수행시각 (사용자가 행동한 시간)',
  `log_type` varchar(100) DEFAULT NULL COMMENT '로그유형 (스크립트 첨부파일 열람, 이메일 열람2 등)',
  `mail_type` varchar(100) DEFAULT NULL COMMENT '메일유형 (퇴직연금 운용, 세금계산서, 카카오톡 등)',
  `target_email` varchar(255) DEFAULT NULL COMMENT '대상 이메일 주소',
  `training_result` enum('success','fail','no_response') DEFAULT 'no_response' COMMENT '훈련 결과 (성공, 실패, 무응답)',
  `response_time_minutes` int(11) DEFAULT NULL COMMENT '응답 시간 (분 단위)',
  `notes` text DEFAULT NULL COMMENT '비고',
  `exclude_from_scoring` tinyint(1) DEFAULT 0 COMMENT '점수 계산 제외 여부',
  `exclude_reason` text DEFAULT NULL COMMENT '제외 사유',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`training_id`),
  UNIQUE KEY `uk_user_period_email` (`user_id`,`period_id`,`target_email`),
  KEY `idx_training_year` (`training_year`),
  KEY `idx_training_result` (`training_result`),
  KEY `idx_log_type` (`log_type`),
  KEY `idx_mail_type` (`mail_type`),
  KEY `period_id` (`period_id`),
  KEY `idx_email_sent_time` (`email_sent_time`),
  KEY `idx_action_time` (`action_time`),
  KEY `idx_user_year_result` (`user_id`,`training_year`,`training_result`),
  KEY `idx_target_email` (`target_email`),
  CONSTRAINT `phishing_training_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`) ON DELETE CASCADE,
  CONSTRAINT `phishing_training_ibfk_2` FOREIGN KEY (`period_id`) REFERENCES `phishing_training_periods` (`period_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='피싱 훈련 이력 (엑셀 업로드 매핑)';

CREATE TABLE IF NOT EXISTS `phishing_training_periods` (
  `period_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `training_year` int(11) NOT NULL COMMENT '훈련 연도',
  `period_name` varchar(50) NOT NULL COMMENT '기간명 (1차 피싱 훈련, 2차 피싱 훈련 등)',
  `training_type` varchar(100) NOT NULL COMMENT '훈련 유형 (이메일 피싱, SMS 피싱, 전화 피싱 등)',
  `start_date` date NOT NULL COMMENT '훈련 시작일',
  `end_date` date NOT NULL COMMENT '훈련 종료일',
  `is_completed` tinyint(1) DEFAULT 0 COMMENT '완료 여부',
  `completed_at` timestamp NULL DEFAULT NULL COMMENT '완료 처리 시각',
  `completed_by` varchar(50) DEFAULT NULL COMMENT '완료 처리한 관리자',
  `description` text DEFAULT NULL COMMENT '훈련 설명',
  `auto_pass_setting` tinyint(1) DEFAULT 1 COMMENT '자동 통과 처리 여부',
  `created_by` varchar(50) NOT NULL COMMENT '생성한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`period_id`),
  UNIQUE KEY `uk_year_period_type` (`training_year`,`period_name`,`training_type`),
  KEY `idx_training_year` (`training_year`),
  KEY `idx_training_type` (`training_type`),
  KEY `idx_is_completed` (`is_completed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='피싱 훈련 기간 설정';

CREATE TABLE `phishing_training_stats` (
	`training_year` INT(11) NOT NULL COMMENT '훈련 연도',
	`period_id` BIGINT(20) NOT NULL COMMENT '훈련 기간 ID 참조',
	`period_name` VARCHAR(1) NOT NULL COMMENT '기간명 (1차 피싱 훈련, 2차 피싱 훈련 등)' COLLATE 'utf8mb4_unicode_ci',
	`training_type` VARCHAR(1) NOT NULL COMMENT '훈련 유형 (이메일 피싱, SMS 피싱, 전화 피싱 등)' COLLATE 'utf8mb4_unicode_ci',
	`total_targets` BIGINT(21) NOT NULL,
	`success_count` BIGINT(21) NOT NULL,
	`fail_count` BIGINT(21) NOT NULL,
	`no_response_count` BIGINT(21) NOT NULL,
	`success_rate` DECIMAL(26,2) NULL,
	`fail_rate` DECIMAL(26,2) NULL
);

CREATE TABLE IF NOT EXISTS `security_education` (
  `education_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `education_year` int(11) NOT NULL COMMENT '교육 연도',
  `course_name` varchar(200) NOT NULL COMMENT 'CSV의 수강과정 컬럼 값',
  `completed_count` int(11) DEFAULT 0 COMMENT 'CSV의 수료 컬럼 값',
  `incomplete_count` int(11) DEFAULT 0 COMMENT 'CSV의 미수료 컬럼 값',
  `total_courses` int(11) GENERATED ALWAYS AS (`completed_count` + `incomplete_count`) STORED COMMENT '전체 과정 수',
  `completion_rate` decimal(5,2) GENERATED ALWAYS AS (case when `completed_count` + `incomplete_count` = 0 then 0 else round(`completed_count` / (`completed_count` + `incomplete_count`) * 100,2) end) STORED COMMENT '수료율 (%)',
  `education_type` varchar(100) DEFAULT '기본교육' COMMENT '교육 유형 (참고용)',
  `education_date` date DEFAULT NULL COMMENT '교육 수료일',
  `notes` text DEFAULT NULL COMMENT '비고',
  `period_id` bigint(20) DEFAULT NULL COMMENT '교육 기간 ID 참조',
  `exclude_from_scoring` tinyint(1) DEFAULT 0 COMMENT '점수 계산 제외 여부',
  `exclude_reason` text DEFAULT NULL COMMENT '제외 사유',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`education_id`),
  UNIQUE KEY `uk_user_period_course` (`user_id`,`period_id`,`course_name`),
  KEY `idx_education_year` (`education_year`),
  KEY `idx_completion_rate` (`completion_rate`),
  KEY `period_id` (`period_id`),
  CONSTRAINT `security_education_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`) ON DELETE CASCADE,
  CONSTRAINT `security_education_ibfk_2` FOREIGN KEY (`period_id`) REFERENCES `security_education_periods` (`period_id`),
  CONSTRAINT `CONSTRAINT_1` CHECK (`completed_count` >= 0),
  CONSTRAINT `CONSTRAINT_2` CHECK (`incomplete_count` >= 0),
  CONSTRAINT `CONSTRAINT_3` CHECK (`completed_count` + `incomplete_count` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정보보호 교육 이력 (CSV 매핑 개선 버전)';

CREATE TABLE IF NOT EXISTS `security_education_periods` (
  `period_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `education_year` int(11) NOT NULL COMMENT '교육 연도',
  `period_name` varchar(50) NOT NULL COMMENT '기간명 (1차 오프라인, 2차 온라인 등)',
  `education_type` varchar(100) NOT NULL COMMENT '교육 유형 (오프라인, 온라인, 신입교육 등)',
  `start_date` date NOT NULL COMMENT '교육 시작일',
  `end_date` date NOT NULL COMMENT '교육 종료일',
  `is_completed` tinyint(1) DEFAULT 0 COMMENT '완료 여부',
  `completed_at` timestamp NULL DEFAULT NULL COMMENT '완료 처리 시각',
  `completed_by` varchar(50) DEFAULT NULL COMMENT '완료 처리한 관리자',
  `description` text DEFAULT NULL COMMENT '교육 설명',
  `auto_pass_setting` tinyint(1) DEFAULT 1 COMMENT '자동 통과 처리 여부',
  `created_by` varchar(50) NOT NULL COMMENT '생성한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`period_id`),
  UNIQUE KEY `uk_year_period_type` (`education_year`,`period_name`,`education_type`),
  KEY `idx_education_year` (`education_year`),
  KEY `idx_education_type` (`education_type`),
  KEY `idx_is_completed` (`is_completed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정보보호 교육 기간 설정';

CREATE TABLE IF NOT EXISTS `security_score_summary` (
  `summary_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `evaluation_year` int(11) NOT NULL COMMENT '평가 연도',
  `audit_penalty` decimal(5,2) DEFAULT 0.00 COMMENT '감사 감점 (실패 항목 * 0.5)',
  `education_penalty` decimal(5,2) DEFAULT 0.00 COMMENT '교육 감점 (미완료 기간당 0.5점)',
  `training_penalty` decimal(5,2) DEFAULT 0.00 COMMENT '모의훈련 감점 (실패 * 0.5)',
  `total_penalty` decimal(5,2) DEFAULT 0.00 COMMENT '총 감점 (최대 -5.0점)',
  `audit_failed_count` int(11) DEFAULT 0 COMMENT '감사 실패 항목 수',
  `education_incomplete_count` int(11) DEFAULT 0 COMMENT '미완료 교육 기간 수 (0.5점씩 감점)',
  `training_failed_count` int(11) DEFAULT 0 COMMENT '모의훈련 실패 횟수',
  `last_calculated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`summary_id`),
  UNIQUE KEY `uk_user_year` (`user_id`,`evaluation_year`),
  KEY `idx_evaluation_year` (`evaluation_year`),
  CONSTRAINT `fk_score_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='KPI 보안 점수 요약 (교육 기간별 감점 기준)';

CREATE TABLE IF NOT EXISTS `user_exceptions` (
  `exception_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `item_id` varchar(255) NOT NULL COMMENT '항목 ID (audit: 숫자, education/training: 문자열)',
  `item_type` enum('audit','education','training') NOT NULL COMMENT '항목 유형',
  `item_name` varchar(255) NOT NULL COMMENT '항목명',
  `item_category` varchar(100) NOT NULL COMMENT '항목 카테고리',
  `exclude_reason` varchar(255) NOT NULL COMMENT '제외 사유',
  `exclude_type` enum('permanent','temporary') DEFAULT 'permanent' COMMENT '제외 유형',
  `start_date` date DEFAULT NULL COMMENT '제외 시작일 (temporary인 경우)',
  `end_date` date DEFAULT NULL COMMENT '제외 종료일 (temporary인 경우)',
  `created_by` varchar(50) NOT NULL COMMENT '설정한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  PRIMARY KEY (`exception_id`),
  UNIQUE KEY `uk_user_item_exception` (`user_id`,`item_id`,`item_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_item_type` (`item_type`),
  KEY `idx_active` (`is_active`),
  KEY `idx_user_exceptions_search` (`user_id`,`item_type`,`is_active`),
  KEY `idx_item_search` (`item_id`,`item_type`),
  CONSTRAINT `fk_user_exception` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='통합 사용자별 예외 설정 테이블';

CREATE TABLE IF NOT EXISTS `user_extended_exceptions` (
  `exception_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `item_id` varchar(100) NOT NULL COMMENT '항목 ID (정수형: 감사항목, 문자형: 교육/훈련)',
  `item_type` enum('audit_item','training_period','education_period') NOT NULL COMMENT '항목 유형',
  `item_name` varchar(255) NOT NULL COMMENT '항목명 (비정규화)',
  `item_category` varchar(100) NOT NULL COMMENT '항목 카테고리 (비정규화)',
  `exclude_reason` varchar(500) NOT NULL COMMENT '제외 사유',
  `exclude_type` enum('permanent','temporary') DEFAULT 'permanent' COMMENT '제외 유형',
  `start_date` date DEFAULT NULL COMMENT '제외 시작일 (temporary인 경우)',
  `end_date` date DEFAULT NULL COMMENT '제외 종료일 (temporary인 경우)',
  `created_by` varchar(50) NOT NULL COMMENT '설정한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  PRIMARY KEY (`exception_id`),
  UNIQUE KEY `uk_user_extended_exception` (`user_id`,`item_id`,`item_type`),
  KEY `idx_user_id_extended` (`user_id`),
  KEY `idx_item_type_extended` (`item_type`),
  KEY `idx_active_extended` (`is_active`),
  KEY `idx_item_category` (`item_category`),
  KEY `idx_user_extended_search` (`user_id`,`item_type`,`is_active`),
  CONSTRAINT `fk_user_extended_exception` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자별 확장 감사 항목 제외 설정 (감사/교육/훈련)';

CREATE TABLE IF NOT EXISTS `user_item_exceptions` (
  `exception_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL COMMENT 'users 테이블의 uid 참조',
  `item_id` int(11) NOT NULL COMMENT 'checklist_items 테이블 참조',
  `exclude_reason` varchar(255) NOT NULL COMMENT '제외 사유',
  `exclude_type` enum('permanent','temporary') DEFAULT 'permanent' COMMENT '제외 유형',
  `start_date` date DEFAULT NULL COMMENT '제외 시작일 (temporary인 경우)',
  `end_date` date DEFAULT NULL COMMENT '제외 종료일 (temporary인 경우)',
  `created_by` varchar(50) NOT NULL COMMENT '설정한 관리자',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1 COMMENT '활성 상태',
  `item_type` varchar(50) DEFAULT 'audit' COMMENT '항목 유형 (audit/education/training)',
  `item_name` varchar(255) DEFAULT '' COMMENT '항목명 (중복 저장)',
  `item_category` varchar(100) DEFAULT '' COMMENT '항목 카테고리 (중복 저장)',
  PRIMARY KEY (`exception_id`),
  UNIQUE KEY `uk_user_item_exception` (`user_id`,`item_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_active` (`is_active`),
  KEY `idx_user_exceptions_type` (`user_id`,`item_type`,`is_active`),
  CONSTRAINT `fk_exception_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`uid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자별 감사 항목 제외 설정';

CREATE TABLE `user_phishing_summary` (
	`user_id` BIGINT(20) NOT NULL COMMENT 'JPA에서 Long 타입으로 매핑',
	`username` VARCHAR(1) NOT NULL COMMENT '사용자 로그인 ID' COLLATE 'utf8mb4_unicode_ci',
	`department` VARCHAR(1) NULL COMMENT '소속 부서' COLLATE 'utf8mb4_unicode_ci',
	`email` VARCHAR(1) NULL COMMENT '이메일 주소' COLLATE 'utf8mb4_unicode_ci',
	`training_year` INT(11) NULL COMMENT '훈련 연도',
	`total_trainings` BIGINT(21) NOT NULL,
	`success_count` BIGINT(21) NOT NULL,
	`fail_count` BIGINT(21) NOT NULL,
	`no_response_count` BIGINT(21) NOT NULL,
	`success_rate` DECIMAL(26,2) NULL,
	`penalty_score` DECIMAL(22,1) NOT NULL
);

CREATE TABLE IF NOT EXISTS `users` (
  `uid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'JPA에서 Long 타입으로 매핑',
  `user_id` varchar(50) NOT NULL COMMENT '사용자 로그인 ID',
  `username` varchar(50) NOT NULL COMMENT '사용자 실명',
  `mail` varchar(255) DEFAULT NULL COMMENT '이메일 주소',
  `department` varchar(100) DEFAULT NULL COMMENT '소속 부서',
  `created_at` timestamp NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일시',
  `last_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '최종 업데이트 (기존 호환)',
  `ip` text DEFAULT NULL COMMENT 'IP 주소 (여러개인 경우 쉼표로 구분)',
  `mac` text DEFAULT NULL COMMENT 'MAC 주소 (여러개인 경우 쉼표로 구분)',
  `role` enum('admin','user') DEFAULT 'user',
  `is_active` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  KEY `idx_username` (`username`),
  KEY `idx_department` (`department`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 정보';

DROP TABLE IF EXISTS `phishing_training_stats`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `phishing_training_stats` AS select `pt`.`training_year` AS `training_year`,`pt`.`period_id` AS `period_id`,`ptp`.`period_name` AS `period_name`,`ptp`.`training_type` AS `training_type`,count(0) AS `total_targets`,count(case when `pt`.`training_result` = 'success' then 1 end) AS `success_count`,count(case when `pt`.`training_result` = 'fail' then 1 end) AS `fail_count`,count(case when `pt`.`training_result` = 'no_response' then 1 end) AS `no_response_count`,round(count(case when `pt`.`training_result` = 'success' then 1 end) / count(0) * 100,2) AS `success_rate`,round(count(case when `pt`.`training_result` = 'fail' then 1 end) / count(0) * 100,2) AS `fail_rate` from (`phishing_training` `pt` join `phishing_training_periods` `ptp` on(`pt`.`period_id` = `ptp`.`period_id`)) where `pt`.`exclude_from_scoring` = 0 group by `pt`.`training_year`,`pt`.`period_id`,`ptp`.`period_name`,`ptp`.`training_type` 
;

DROP TABLE IF EXISTS `user_phishing_summary`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `user_phishing_summary` AS select `u`.`uid` AS `user_id`,`u`.`user_id` AS `username`,`u`.`department` AS `department`,`u`.`mail` AS `email`,`pt`.`training_year` AS `training_year`,count(0) AS `total_trainings`,count(case when `pt`.`training_result` = 'success' then 1 end) AS `success_count`,count(case when `pt`.`training_result` = 'fail' then 1 end) AS `fail_count`,count(case when `pt`.`training_result` = 'no_response' then 1 end) AS `no_response_count`,round(count(case when `pt`.`training_result` = 'success' then 1 end) / count(0) * 100,2) AS `success_rate`,count(case when `pt`.`training_result` = 'fail' then 1 end) * 0.5 AS `penalty_score` from (`users` `u` left join `phishing_training` `pt` on(`u`.`uid` = `pt`.`user_id` and `pt`.`exclude_from_scoring` = 0)) group by `u`.`uid`,`u`.`user_id`,`u`.`department`,`u`.`mail`,`pt`.`training_year` 
;